### ISSUE TITLE
Inverse Kinematics Arduino Library - meArm

### ISSUE THREAD

**Issue by Dustyoday** [UH-ECE6397/Syllabus#2]
This looks like a useful repository. Inverse kinematics library for meArm and Arduino.
https://github.com/yorkhackspace/meArm?files=1

@UH-ECE6397/students 
@UH-ECE6397/staff

**Comment by AlpNov** [comment]
Forked to UH-ECE6397

**Comment by meakdogan** [comment]
Is There any meeting today ? 

Mehmet Emin Akdogan
